# Python basics
### STAT 601.28: Deep Learning and it's hands-on practice
Qingrun Zhang


# Outline

*  Grammatic convention: Java + R?
*  Typed or not: Static v.s. Dynamic error checking
*   Strings, Lists, Dictionaries and Tuples
*   Broadcasting
*   Slice operator


## Grammatic convention



*   Python is interpreted: Python is processed at runtime by the interpreter. You don't need to compile your program before exceuting it.
*   When initiatting a variable, one doesn't need to clarify the type. However, please be aware that it has a type.










In [1]:
age =16
name ="Frank"
height =1.76
is_girl =False
print(type(age))
print(type(name))
print(type(height))
print(type(is_girl))


<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>




*   Python is interactive, e.g. input function




In [2]:
name =input("what's your name? ")
print("Hello "+name)

Hello li




*   Casting and type conversions

In [ ]:

Birth_year = input("Enter your birth year ")
age =2022-Birth_year

Enter your birth year 1996


TypeError: ignored

In [ ]:
#what your type in the input function is String.
Birth_year = int(input("Enter your birth year ")) 
age =2022-int(Birth_year)
print(age)

Enter your birth year 1986
36


In [ ]:
cfirst =input("First: ")
second =input("Second: ")
sum =float(first)+float(second)
print(sum)
#can't concatenate different datatype
print("Sum: "+sum)
print("Sum: "+str(sum))

First: 23
Second: 39
62.0


TypeError: ignored



*   An object has specific funcitons. For example: a car remote control has multiple funcitons: lock, unlock, alarm etc. 
*   Function refer to an object is called method.
*   Print and input functions are general functions, they don't belong to an object
*   The functions don't change the original String. It will return a new one. We can't change the string once we create it
*   To check whether a string contains charactors, it return the index of that charactor, str.find(), str.rfind()
*   "in" operator

In [ ]:
course ="Deep Learning course"
print(course.upper())
print(course)
print(course.find('e'))
print(course.rfind('e'))
print(course.replace('Deep Learning', 'java'))
print(course.find("Deep Learning"))
print("Deep Learning" in course)


DEEP LEARNING COURSE
Deep Learning course
1
19
java course
0
True




Arithmatic operators, two different divisions

Augmented assignment operator



In [3]:
print(10/3)
print(10//3)
print(10 % 3)
print(10**3)
x = 10
x += 5
x = x+5

3.3333333333333335
3
1
1000


*   Comparasion operators

In [ ]:
x =6>= 1
print(x)
y =7==2
print(y)

True
False


logical operators

"not" will invert the value it gets

In [ ]:
age =21
print(age>14 and age <30)
print(age>14 or age <20)
print(not age>100)

True
True
True


Python using indentation to show a block of code 

In [ ]:
price=35
if price>30:
  print("It's expensive" )
elif price >20: #(20, 30]
  print("It's a reasonable pirce")
elif price >10:
  print("It's a bit cheap")
else:
  print("Is it real?")
print("Done")

It's expensive
Done


Four built-in data types in Python
> List, Set, Dictionary and Tuple

A list a sequence of values which can be characters, integers or even another list.
> Lists are created using square brackets, or using list() constructor to make a list.


In [ ]:
fruit_list=["apple", "banana", "cherry", "pear"]
print(fruit_list)

fruit_list2 = list(("apple", "banana", "cherry", "pear")) # note the double round-brackets
print(fruit_list2) 

['apple', 'banana', 'cherry', 'pear']
['apple', 'banana', 'cherry', 'pear']


List items can be of any data type, even different datatypes

In [ ]:
fruit_list3 =list(("apple", 3, "banana", 4, True))
print(fruit_list3)

['apple', 3, 'banana', 4, True]




List items are ordered, changeable, and allow duplicate values.


In [ ]:
fruit_list = ["apple", "banana", "cherry", "pear", "cherry","apple"]
print(fruit_list[1])
fruit_list[1] ="pear"
print(fruit_list)

banana
['apple', 'pear', 'cherry', 'pear', 'cherry', 'apple']


List length: len() function

In [ ]:
print(len(fruit_list3))

5


Set is a collection which is unordered, unchangeable*, and unindexed. 
No duplicate members. 
Sets are written with curly brackets.

In [ ]:
fruit_set = {"apple", "banana", "cherry"}

for x in fruit_set:
  print(x)

apple
banana
cherry


In [ ]:
print("banana" in fruit_set)

True


Once a set is created, you cannot change its items, but you can add new items.

In [ ]:
print(fruit_set)
fruit_set.add("orange")
print(fruit_set)
fruit_set.remove("banana")
print(fruit_set)

{'banana', 'orange', 'cherry', 'apple'}
{'banana', 'orange', 'cherry', 'apple'}
{'orange', 'cherry', 'apple'}


Join sets

In [ ]:
count_set = {1, 2, 3}
fruit_count_set = fruit_set.union(count_set)
print(fruit_count_set)

{1, 2, 3, 'cherry', 'apple', 'banana'}


The update() method inserts the items of set2 into set1:
More methods: https://www.w3schools.com/python/python_sets_methods.asp

In [ ]:
print(count_set)
count_set.update(fruit_set)
print(count_set)

{1, 2, 3}
{1, 2, 3, 'cherry', 'apple', 'banana'}


Dictionaries are used to store data values in key:value pairs and can be referred to by using the key name

Dictionary items are ordered (since Python 3.7), changeable, and does not allow duplicates. 

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Escape SE",
  "year": 2015
}
print(thisdict)

{'brand': 'Ford', 'model': 'Escape SE', 'year': 2015}


Access, change, add, remove items in dictionary

In [ ]:
x =thisdict.keys()
print(type(x))
print(x)
y = thisdict.get("brand")
print(y)
thisdict["year"] =2017
print(thisdict)
thisdict["color"] ="black"
print(thisdict)
thisdict.update({"price" : "23000"})
print(thisdict)
thisdict.pop("color")
print(thisdict)

<class 'dict_keys'>
dict_keys(['brand', 'model', 'year', 'color', 'price'])
Ford
{'brand': 'Ford', 'model': 'Escape SE', 'year': 2017, 'color': 'black', 'price': '23000'}
{'brand': 'Ford', 'model': 'Escape SE', 'year': 2017, 'color': 'black', 'price': '23000'}
{'brand': 'Ford', 'model': 'Escape SE', 'year': 2017, 'color': 'black', 'price': '23000'}
{'brand': 'Ford', 'model': 'Escape SE', 'year': 2017, 'price': '23000'}


Loop dictionary

In [ ]:
for x in thisdict:
  print(thisdict[x])

Ford
Escape SE
2017
23000


In [ ]:
for x in thisdict:
  print(x)

brand
model
year
price


In [ ]:
for x in thisdict.keys():
  print(x)

brand
model
year
price


In [ ]:
for x in thisdict.items():
  print(x)

('brand', 'Ford')
('model', 'Escape SE')
('year', 2017)
('price', '23000')


Tuple is ordered, unchangable and allow duplicate values. 


In [ ]:
fruit_tuple=("apple", "banana")
print(fruit_tuple)
fruit_tuple2=tuple(("cherry","pear")) #not the double round-brackets

('apple', 'banana')


Tuple: unchangeable, meaning that we cannot change, add or remove items after the tuple has been created

In [ ]:
print(fruit_tuple[1])
fruit_tuple[1] ="grape"

banana


TypeError: ignored

In [ ]:
y=list(fruit_tuple)
y[1]="grape"
fruit_tuple=tuple(y)
print(fruit_tuple)

Loop tuples

In [ ]:
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

apple
banana
cherry


Join and multiply tuples

In [ ]:
fruits=("apple", "banana","cherry")
counts =(1,2,3)
fruit_count=fruits+counts
print(fruit_count)
myfruits =fruits*2
print(myfruits)

('apple', 'banana', 'cherry', 1, 2, 3)
('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


NumPy is used for working with arrays.

Create a basic array: np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
b=np.zeros(3)
print(b)

[0. 0. 0.]


In [ ]:
d=np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
e=np.arange(2, 20, 4)
print(e)

[ 2  6 10 14 18]


In [ ]:
f= np.linspace(1, 10, num=4)
print(f)

[ 1.  4.  7. 10.]


In [ ]:
g = np.ones(2, dtype=np.float32)
print(g)

[1. 1.]


In [ ]:
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [ ]:
# simple indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])


One key difference is that you can use negative indexes to retrieve values offset from the end of the array.

In [ ]:
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


In [ ]:
# 2d indexing
from numpy import array
# define array
data = array([[11, 22], [33, 44], [55, 66]])
# index data
print(data[1,0])

33


Array Slicing: data[from:to]

In [ ]:
data = array([1, 2, 3, 4, 5])
print(data[0:1])

[1]


In [ ]:
from numpy import array
data = array([[1, 2, 3],
		[4, 5, 6],
		[7, 8, 9]])
# separate data
X, y = data[:, :-1], data[:, -1]
print("x: ", X)
print("y: ", y)

x:  [[1 2]
 [4 5]
 [7 8]]
y:  [3 6 9]


In [ ]:
from numpy import array
data = array([[1, 2, 3, 4, 5],
		[6,7,8,9,10],
		[11, 12, 13,14,15]])
# separate data
split = 3
train,test = data[:, : split],data[:, split:]
print("train ", train)
print("test ", test)

train  [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
test  [[ 4  5]
 [ 9 10]
 [14 15]]


# Reshaping and flattening multidimensional arrays

Array Reshaping: It is important to reshape your NumPy arrays to meets the expectation of specific Python libraries

In [1]:
from numpy import array
from numpy import reshape
# define array
data = array([1, 2, 3, 4, 5])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


In [ ]:
from numpy import array
data = array([[1, 2, 3],
		[4, 5, 6],
		[7, 8, 9]])
print(data.shape)
# reshape
data = data.reshape((1, data.shape[0], data.shape[1]))
print(data.shape)

(3, 3)
(1, 3, 3)


Broad Casting

In [ ]:
#the scalar b being stretched during the arithmetic operation into an array with the same shape as a. 
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b=2
print(a*b)


[2. 4. 6.]


In [2]:
a = array([[ 0.0,  0.0,  0.0],
           [1.0, 1.0, 1.0],
           [2.0, 2.0, 2.0],
           [3.0, 3.0, 3.0]])
b = array([1.0, 2.0, 3.0])
print(a.shape)
print(b.shape)
print(a + b)

(4, 3)
(3,)
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


In [ ]:
c = array([1,2,3,4])
print(a+c)

ValueError: ignored

Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3])
c = a[:, np.newaxis] + b
print(c)

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [ ]:
d=a[:, np.newaxis] *b
print(d)
print(a[:, np.newaxis].shape)
print(b.shape)

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]
(4, 1)
(3,)


In [2]:
import numpy as np
a = np.random.rand(3,3)
b = np.random.rand(2,1)
c= a+b


ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 