NumPy is a Linear Algebra Library used for multidimensional arrays

Let's define a one-dimensional array

https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/tensor.ipynb


In [ ]:
import numpy as np
#list is collection of elements, could be numbers strings etc
list1=[2,1,4,600,100,200,300,400]
list1


[2, 1, 4, 600, 100, 200, 300, 400]

In [ ]:
#from list create numpy array
nparray =np.array(list1)
nparray

array([  2,   1,   4, 600, 100, 200, 300, 400])

In [ ]:
type(nparray)

numpy.ndarray

In [ ]:
#create a high dimensional matrix. Define a matrix, it is defined on a row by row basis
my_matrix =np.array([[1,2,3],[4,5,6]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
x=np.random.rand(20)
x

array([0.06548954, 0.02805905, 0.05641816, 0.66372118, 0.12008126,
       0.24169751, 0.53360402, 0.83208838, 0.43452103, 0.84807626,
       0.93407321, 0.77179703, 0.87285185, 0.20397621, 0.88083307,
       0.15971149, 0.41910936, 0.16825693, 0.34419954, 0.51182187])

In [ ]:
#np.random.rand(d0, d1....)
np.random.rand(3,2)


array([[0.65224844, 0.90378795],
       [0.73909165, 0.16855692],
       [0.61405664, 0.15167445]])

In [ ]:
#random.randint(low, high=None, size=None, dtype=int)
#Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” 
#interval [low, high). If high is None (the default), then results are from [0, low).
np.random.randint(50)

1

In [ ]:
np.random.randint(5, size=(2, 4))

array([[2, 3, 4, 4],
       [0, 2, 1, 1]])

In [ ]:
np.random.randint(5, size=10)

array([0, 0, 0, 3, 3, 0, 4, 4, 4, 3])

In [ ]:
#numpy.arange([start, ]stop, [step), integer steps
np.arange(1,40, step=2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [ ]:
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
np.linspace(2.0, 3.0, num=5, endpoint=False)


array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
#takes in an positive interger x from the user, then create 1x4 array with randome number ranging from 0 to x
x = int(input('please enter a positive integer value')) # casting


please enter a positive integer value43


In [ ]:
x

43

In [ ]:
np.random.randint(1,x, 4)

array([15, 27,  2, 12])

Mathematical operations with numpy

In [ ]:
x=np.arange(1,10)
y=np.arange(10, 20)
x+y

ValueError: ignored

In [ ]:
x=np.arange(1,10)
y=np.arange(10, 19)
x+y

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [ ]:
#broadcast
x=np.arange(1,10)
y=[1]
x+y

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#square the elements of any array
x**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.sqrt(x**2)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#get exponential e^x
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [ ]:
#get the distance between them
x=np.arange(1,10)
y=np.arange(10, 19)
np.sqrt(x**2+y**2)


array([10.04987562, 11.18033989, 12.36931688, 13.60147051, 14.86606875,
       16.15549442, 17.4642492 , 18.78829423, 20.1246118 ])

Array Slicing and Indexing

In [ ]:
my_np_array=np.array([2,4,6,8,10])
my_np_array

array([ 2,  4,  6,  8, 10])

In [ ]:
my_np_array[0]

2

In [ ]:
my_np_array[-2]

8

In [ ]:
my_np_array[0:3] #start from index 0 up until not including 3

array([2, 4, 6])

In [ ]:
#broadcasting, altering several values in an np array at once
my_np_array[0:3]=5
my_np_array

array([ 5,  5,  5,  8, 10])

In [ ]:
matrix=np.random.randint(1, 10,(5,5))
matrix

array([[9, 1, 8, 6, 1],
       [5, 3, 8, 6, 9],
       [6, 9, 7, 2, 1],
       [6, 2, 1, 4, 3],
       [2, 7, 3, 6, 3]])

In [ ]:
matrix[0]

array([9, 1, 8, 6, 1])

In [ ]:
matrix[-1]

array([2, 7, 3, 6, 3])

In [ ]:
matrix[1][2]

8

In [ ]:
#Question: replace last row with zero
matrix[-1]=0
matrix

array([[9, 1, 8, 6, 1],
       [5, 3, 8, 6, 9],
       [6, 9, 7, 2, 1],
       [6, 2, 1, 4, 3],
       [0, 0, 0, 0, 0]])

Elements selection(condition)

In [ ]:
matrix=np.random.randint(1, 10,(5,5))
matrix

array([[1, 4, 3, 1, 4],
       [1, 3, 2, 2, 1],
       [3, 9, 2, 7, 5],
       [4, 8, 6, 6, 1],
       [2, 8, 9, 9, 1]])

In [ ]:
new_matrix=matrix[matrix>5]
new_matrix

array([9, 7, 8, 6, 6, 8, 9, 9])

In [ ]:
new_matrix=matrix[matrix%2==0]
new_matrix

array([4, 4, 2, 2, 2, 4, 8, 6, 6, 2, 8])

In [ ]:
#replace odd elements by -3, replace even elements by 0
matrix[matrix %2==1]=-3
matrix[matrix%2==0] =0

matrix

array([[-3,  0, -3, -3,  0],
       [-3, -3,  0,  0, -3],
       [-3, -3,  0, -3, -3],
       [ 0,  0,  0,  0, -3],
       [ 0,  0, -3, -3, -3]])

Pandas is a data manipulation and analysis tool that is built on Numpy.
Pandas uses data structure (dataframe) to store and manipute data in tabular fashion
Series is considered a single column of a dataframe

In [ ]:
import pandas as pd

In [ ]:
student_df=pd.DataFrame({"student ID":[111,222,333,444],
                         "Student Name":["Aron","Ben","Cathy","Daven"],
                         "Score":[98,90,95,96],
                         "years": [2,3,2,3]})
student_df

student ID Student Name  Score  years
0         111         Aron     98      2
1         222          Ben     90      3
2         333        Cathy     95      2
3         444        Daven     96      3

In [ ]:
type(student_df)

pandas.core.frame.DataFrame

In [ ]:
student_df.head(2)

student ID Student Name  Score  years
0         111         Aron     98      2
1         222          Ben     90      3

In [ ]:
student_df.tail(2)

student ID Student Name  Score  years
2         333        Cathy     95      2
3         444        Daven     96      3

Mini Challenge
1. Create a dataframe named stock_df that has 4 different stock, number of shares and price per share
2. Calculate the total value of the stocks

In [ ]:
stock_df=pd.DataFrame({"Stock Symbol":["APPL","AMZN","TESLA","HD" ],
                       "price per share $": [130, 105, 645, 272],
                       "number of shares":[2,5,8,6]})
stock_df

Stock Symbol  price per share $  number of shares
0         APPL                130                 2
1         AMZN                105                 5
2        TESLA                645                 8
3           HD                272                 6

In [ ]:
stock =stock_df['price per share $']*stock_df['number of shares']
stock

0     260
1     525
2    5160
3    1632
dtype: int64

PANDAS with CSV and HTML data



In [ ]:
#house_index=pd.read_(contr+space)
#When you run this cell, you might get an error list stating that L XML is not found.
#So please make sure run !pip install lxml  and !python -m pip instll --upgrade pip, and then restart the kernel
city_population_df=pd.read_html('https://worldpopulationreview.com/countries/cities/canada')
city_population_df[0] # if have multiple table use the index to access the tables

Name  2022 Population
0                Toronto          2600000
1               Montreal          1600000
2                Calgary          1019942
3                 Ottawa           812129
4               Edmonton           712391
..                   ...              ...
395  Etobicoke West Mall            11848
396       Yonge-Eglinton            11817
397       Dufferin Grove            11785
398            Montmagny            11724
399               Gander            11688

[400 rows x 2 columns]

In [ ]:
large_cities=city_population_df[0][city_population_df[0]['2022 Population']>1000000]
large_cities

Name  2022 Population
0   Toronto          2600000
1  Montreal          1600000
2   Calgary          1019942

In [ ]:
student_df

student ID Student Name  Score  years
0         111         Aron     98      2
1         222          Ben     90      3
2         333        Cathy     95      2
3         444        Daven     96      3

In [ ]:
del student_df['years']
student_df

student ID Student Name  Score
0         111         Aron     98
1         222          Ben     90
2         333        Cathy     95
3         444        Daven     96

In [ ]:
student_df['Score'].sum()

379

In [ ]:
student_df.insert(3,"Score2",[79,87,76,90], True)
student_df

student ID Student Name  Score  Score2
0         111         Aron     98      79
1         222          Ben     90      87
2         333        Cathy     95      76
3         444        Daven     96      90

In [ ]:
student_df = student_df.rename(columns={"Score": "Score1"})

In [ ]:
def socre1update(scores):
  return scores*0.9

In [ ]:
student_df['Score1'].apply(socre1update)


0    88.2
1    81.0
2    85.5
3    86.4
Name: Score1, dtype: float64

Sorting and ordering with Pandas

In [ ]:
student_df.sort_values(by ="Score2")

student ID Student Name  Score1  Score2
2         333        Cathy      95      76
0         111         Aron      98      79
1         222          Ben      90      87
3         444        Daven      96      90

In [ ]:
student_df

student ID Student Name  Score1  Score2
0         111         Aron      98      79
1         222          Ben      90      87
2         333        Cathy      95      76
3         444        Daven      96      90

In [ ]:
student_df.sort_values(by ="Score2", inplace=True)

In [ ]:
student_df

student ID Student Name  Score1  Score2
2         333        Cathy      95      76
0         111         Aron      98      79
1         222          Ben      90      87
3         444        Daven      96      90

Concatenating and Merging with Pandas

In [ ]:
student_df2=pd.DataFrame({'student ID':[555,666], 'Student Name':['Jace', 'Sandy'], 'Score1':[78, 90], 'Score2': [30, 89]})
student_df2

student ID Student Name  Score1  Score2
0         555         Jace      78      30
1         666        Sandy      90      89

In [ ]:
pd.concat([student_df,student_df2])

student ID Student Name  Score1  Score2
2         333        Cathy      95      76
0         111         Aron      98      79
1         222          Ben      90      87
3         444        Daven      96      90
0         555         Jace      78      30
1         666        Sandy      90      89

In [ ]:
student_df2=pd.DataFrame({'student ID':[555,666], 
                          'Student Name':['Jace', 'Sandy'], 
                          'Score1':[78, 90], 
                          'Score3': [30, 89]},
                         index=[5,6])


In [ ]:
pd.concat([student_df,student_df2])

student ID Student Name  Score1  Score2  Score3
2         333        Cathy      95    76.0     NaN
0         111         Aron      98    79.0     NaN
1         222          Ben      90    87.0     NaN
3         444        Daven      96    90.0     NaN
5         555         Jace      78     NaN    30.0
6         666        Sandy      90     NaN    89.0

In Class Practice

1.   Define a dataframe named "credit_card_df1" that contains the first and last name for 5 clients with IDs=1,2,3,4,5
2.   Assume that we got 3 new clients, sefine another dataframe that contains the new clients with IDs =6,7,8
3.   Let's assume we get new information (Annual Salary) about all the customers
4.   Concatenate both dataframes
5.   Merge client names and their newly added salary information using the client ID









